## Julen Lopetegui as Spain Coach

Here we will visualize the impact that Julen Lopetegui has had on Spanish football in terms of young talent and it's promotion. 

Beautifulsoup package has been used for parsing web pages. [1]

**Note:** Year column is the start of the season. So, Year 2016 is 16-17 season.

In [2]:
import requests # HTTP requests library
from bs4 import BeautifulSoup # for parsing html pages.
import pandas as pd

# Data Scraping

In [39]:
def get_team_data_per_year(year):
    url = "https://www.transfermarkt.co.uk/spain/leistungsdaten/verein/3375/plus/0?reldata=%26{}".format(year)
    pageTree = requests.get(url, headers={'User-Agent': 'Mozilla/5.0'})
    pageSoup = BeautifulSoup(pageTree.content, 'html5lib')
    players = pageSoup.find_all("span", {"class": "hide-for-small"})
    minutes_played = pageSoup.find_all("td", {"class": "rechts "})
    tableItems = pageSoup.find_all("td", {"class": "zentriert"})
    ages = tableItems[1::6]
    players_list = []
    ages_list = []
    minutes_played_list = []
    i = 1
    j = 0
    try:
        while True:
            players_list.append(players[i].a.text)
            ages_list.append(ages[j].text)
            minutes_played_list.append(minutes_played[j].text)
            i += 1
            j += 1
    except:
        print("Page Parsed - {}".format(year))    

    df = pd.DataFrame({"Player":players_list, 
                       "Age":ages_list, 
                       "{}".format(year):minutes_played_list}, 
                      columns=("Player","Age","{}".format(year)))
    df.set_index("Player", inplace=True)
    return df

In [36]:
def get_all_data_given_range(func, year_start, year_end):
    df = func(year_start)
    for year in range(year_start+1, year_end+1):
        df = pd.merge(df, func(year), left_index=True, right_index=True, how='outer', on='Age')
    return df

In [37]:
all_data = get_all_data_given_range(get_team_data_per_year, 1920, 2017)

Page Parsed.
Page Parsed.
Page Parsed.
Page Parsed.
Page Parsed.
Page Parsed.
Page Parsed.
Page Parsed.
Page Parsed.
Page Parsed.
Page Parsed.
Page Parsed.
Page Parsed.
Page Parsed.
Page Parsed.
Page Parsed.
Page Parsed.
Page Parsed.
Page Parsed.
Page Parsed.
Page Parsed.
Page Parsed.
Page Parsed.
Page Parsed.
Page Parsed.
Page Parsed.
Page Parsed.
Page Parsed.
Page Parsed.
Page Parsed.
Page Parsed.
Page Parsed.
Page Parsed.
Page Parsed.
Page Parsed.
Page Parsed.
Page Parsed.
Page Parsed.
Page Parsed.
Page Parsed.
Page Parsed.
Page Parsed.
Page Parsed.
Page Parsed.
Page Parsed.
Page Parsed.
Page Parsed.
Page Parsed.
Page Parsed.
Page Parsed.
Page Parsed.
Page Parsed.
Page Parsed.
Page Parsed.
Page Parsed.
Page Parsed.
Page Parsed.
Page Parsed.
Page Parsed.
Page Parsed.
Page Parsed.
Page Parsed.
Page Parsed.
Page Parsed.
Page Parsed.
Page Parsed.
Page Parsed.
Page Parsed.
Page Parsed.
Page Parsed.
Page Parsed.
Page Parsed.
Page Parsed.
Page Parsed.
Page Parsed.
Page Parsed.
Page Parsed.
Page Parsed.
Page Parsed.
Page Parsed.
Page Parsed.
Page Parsed.
Page Parsed.
Page Parsed.
Page Parsed.
Page Parsed.
Page Parsed.
Page Parsed.
Page Parsed.
Page Parsed.
Page Parsed.
Page Parsed.
Page Parsed.
Page Parsed.
Page Parsed.
Page Parsed.
Page Parsed.
Page Parsed.

In [48]:
all_data.tail()

,Age,1920,1921,1922,1923,1924,1925,1926,1927,1928,...,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017
Player,,,,,,,,,,,,,,,,,,,,,
Ángel Cuéllar,21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Ángel López,25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Ángel María Villar,24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Óscar Téllez,25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Óscar de Marcos,26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-,NaN,NaN

## Visualizing chances/goals (on an average) by Spanish under 25 players, over the years

References:
1. https://fcpython.com/blog/introduction-scraping-data-transfermarkt
2. https://www.digitalocean.com/community/tutorials/how-to-scrape-web-pages-with-beautiful-soup-and-python-3